---
title: "Econometrie"
author: "Félix Bajard"
date: "08/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list = ls())
setwd('/home/felix/Documents/R/')
library(car)
library(lmtest)
library(AER)
library(fBasics)
library(ggplot2)
library(Hmisc)
library(readstata13)
library(tidyverse) 
library(maxLik)
library(micEcon)
```

Importing the databases

```{r read}
city <- read.dta13("citydata.dta",nonint.factors = TRUE)
country <- read.dta13("countrydata.dta",nonint.factors = TRUE)
countryally <- read.dta13("countrydata_allyears.dta",nonint.factors = TRUE)
region <- read.dta13("regiondata.dta",nonint.factors = TRUE)
```



```{r basic stats}
ggplot(country, aes(year,sm0_2moistu, colour=iso3v10, group=iso3v10)) + geom_point() +geom_line()
#urbanization rate
for (i in 2:60){
  if (country$iso3v10[i-1]==country$iso3v10[i]){
    country$urbgrowth[i] <- (country$urbfrac[i]-country$urbfrac[i-1])/country$urbfrac[i-1] 
    country$moistgrowth[i] <- (country$sm0_2moistu[i]-country$sm0_2moistu[i-1])/country$sm0_2moistu[i-1] 
    country$tempgrowth[i] <- (country$sm0_2tmpu[i]-country$sm0_2tmpu[i-1])/country$sm0_2tmpu[i-1] 
    country$precgrowth[i] <- (country$sm0_2preu[i]-country$sm0_2preu[i-1])/country$sm0_2preu[i-1] 
  }
}
country$urbgrowth[36]<- NA #valeur énorme par rapport aux autres fausse
reg1 <- lm(moistgrowth ~ urbgrowth, data = country)
summary(reg1)
ggplot(country, aes(urbgrowth,moistgrowth))+geom_point()+geom_smooth()
reg2 <- lm(tempgrowth ~ urbgrowth, data = country)
summary(reg2)
ggplot(country, aes(urbgrowth,tempgrowth))+geom_point()+geom_smooth()
reg3 <- lm(precgrowth ~ urbgrowth, data = country)
summary(reg3)
ggplot(country, aes(urbgrowth,precgrowth))+geom_point()+geom_smooth()
#pas de corrélation observée au niveau national
#aucune relation significative et R-squared ridicules
reg9 <- lm (urbpop ~ tmpu + petu + preu + year + totpop + centdistcoast + extent_agH + extent_agE, data = region)
summary(reg9)

reg10 <- lm(urbpop ~ tmpu + petu + preu + year + totpop, data = region)
summary(reg10)

reg11 <- lm(urbpop ~ ADsm0_2moistu + ADsm0_2tmpu + ADsm0_2preu + year + totpop + primurbpop + sum_agH + sum_agE, data = country)
summary(reg11)

reg12 <- lm(lnl1 ~ agidison + lnrain30 + hirain + extent_agE + extent_agH, data = city)
summary(reg12)

reg13 <- lm(dlnl1 ~ year + dlnrain30 + D_ag30 + hirain_extent_agH_dlnrain + hirain_extent_agE_dlnrain, data = city)
summary(reg13)

reg14 <- lm(dlnl1 ~ year + agidison + dlnrain30 + D_ag30 + hirain_extent_agH_dlnrain + hirain_extent_agE_dlnrain, data = city)
summary(reg14)

reg15 <- lm(dlnl1 ~ year + agidison + dlnrain30 + D_ag30 + extent_agH + extent_agE + hirain_extent_agH_dlnrain + hirain_extent_agE_dlnrain, data = city)
summary(reg15)
```
